spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:calendardb
    username: sa
    password:

  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
      generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

server:
  port: 8080
